course/course/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls')),
    path('category/', include('main.urls')),
    path('card/', include('django.contrib.auth.urls')),
    path('categorycard/', include('django.contrib.auth.urls')),
    path('recomendation/', include('main.urls')),
    path('createrecom/', include('main.urls')),
    path('tableproduct/', include('main.urls')),
    path('createrecipe/', include('main.urls')),
    path('dictionary/', include('main.urls')),
    path('dashboard/', include('main.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
print(settings.BASE_DIR, settings.MEDIA_ROOT)

course/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index),
    path('category/', views.category),
    path('card/<int:pk>/', views.cardDetailView.as_view(), name='recipe-detail'),
    path('categorycard/<int:pk>/', views.categorycardDetailView.as_view(), name='category-detail'),
    path('recomendation/', views.recom),
    path('createrecom/', views.createrecom),
    path('tableproduct/', views.tablepr),
    path('createrecipe/', views.createrecipe),
    path('dictionary/', views.dictionary),
    path('equipmentTips/', views.equipmentTips),
    path('dashboard/', views.dashboard_with_pivot, name='dashboard_with_pivot'),
    path('dashboard/data/', views.pivot_data, name='pivot_data'),
]

course/main/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.urls import reverse


class TypeIngredient(models.Model):
   # IDtype = models.ForeignKey(Ingredients, on_delete=models.CASCADE, primary_key=True)
    IDtype = models.AutoField(primary_key=True)
    Name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.IDtype)

    class Meta:
        verbose_name = 'ID Типа'
        verbose_name_plural = 'ID Типа'


class Ingredients(models.Model):
    IngredientsID = models.AutoField(primary_key=True)
    NameIngredients = models.TextField()
    Kkal = models.IntegerField()
    Proteins = models.IntegerField()
    Fats = models.IntegerField()
    Carbohydrates = models.IntegerField()
    IDtype = models.ForeignKey(TypeIngredient, on_delete=models.CASCADE, null=True, blank=True)
    # IDtype = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.NameIngredients

    class Meta:
        verbose_name = 'Ингредиент'
        verbose_name_plural = 'Ингредиенты'


class Category(models.Model):
    CategoryID = models.AutoField(primary_key=True)
    Name = models.CharField(max_length=100)
    Img = models.ImageField(height_field=None, width_field=None, null=True, blank=True)

    def __str__(self):
        return self.Name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('category-detail', kwargs={'pk': self.pk})


class Country(models.Model):
    CountryID = models.AutoField(primary_key=True)
    Name = models.CharField(max_length=100)

    def __str__(self):
        return self.Name

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'


class Dictionary(models.Model):
    DictionaryID = models.AutoField(primary_key=True)
    Name = models.CharField(max_length=100)
    Description = models.TextField()

    def __str__(self):
        return self.Name

    class Meta:
        verbose_name = 'Определение'
        verbose_name_plural = 'Определения'


class Recipe(models.Model):
    RecipeID = models.AutoField(primary_key=True)
    Name = models.CharField(max_length=100)
    Instruction = models.TextField()
    Img = models.ImageField(height_field=None, width_field=None, null=True, blank=True)
    CreateDate = models.DateTimeField(auto_now=True)
    CountryID = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.Name

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'

    def get_absolute_url(self):
        return reverse('recipe-detail', kwargs={'pk': self.pk})


class RecipeCategory(models.Model):
    ID = models.AutoField(primary_key=True)
    RecipeID = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    CategoryID = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.ID)

    class Meta:
        verbose_name = 'ID Категории'
        verbose_name_plural = 'ID Категорий'


class IngredientsRecipe(models.Model):
    ID = models.AutoField(primary_key=True)
    RecipeID = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    IngredientsID = models.ForeignKey(Ingredients, on_delete=models.CASCADE)
    CountsOnRecipe = models.CharField(max_length=100)

    def __str__(self):
        return str(self.ID)

    class Meta:
        verbose_name = 'ID Ингредиента'
        verbose_name_plural = 'ID Ингредиентов'


class RecipeUser(models.Model):
    RecipeID = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    Userid = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.RecipeID)

    class Meta:
        verbose_name = 'Автор рецепта'
        verbose_name_plural = 'Авторы рецептов'


class Recommendation(models.Model):
    RecommendationID = models.AutoField(primary_key=True)
    Name = models.CharField(max_length=100)
    Instruction = models.TextField()
    Img = models.ImageField(height_field=None, width_field=None, null=True, blank=True)
    CreateDate = models.DateTimeField(auto_now=True)
    Userid = models.ForeignKey(User, on_delete=models.CASCADE)

    def str(self):
        return f"{self.Name}, {self.CreateDate}"

    class Meta:
        verbose_name = 'Совет'
        verbose_name_plural = 'Советы'


class Rating(models.Model):
    RecipeID = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    Rating = models.IntegerField()
    CountRating = models.IntegerField()

    def str(self):
        rr = Recipe.objects.get(id=self.recipeID_recipeID)
        return f"{rr.recipeID}, {self.rating}"

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинги'


class EquipmentTips(models.Model):
    EquipmentTipsID = models.AutoField(primary_key=True)
    EquipmentTipsName = models.CharField(max_length=100)
    EquipmentTipsDescriptions = models.TextField()
    EquipmentTipsImg = models.ImageField(height_field=None, width_field=None, null=True, blank=True)

    def __str__(self):
        return str(self.EquipmentTipsName)

    class Meta:
        verbose_name = 'Правило'
        verbose_name_plural = 'Правила'

course/main/views.py
from django.shortcuts import render, redirect
from .models import Recipe, Category, Country, Recommendation, IngredientsRecipe, Rating, TypeIngredient, Ingredients, Dictionary, EquipmentTips
from .form import RecommendationForm, RecipeForm
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.core import serializers
from django.views.generic.detail import DetailView



def dashboard_with_pivot(request):
    return render(request, 'main/dashboard_with_pivot.html', {})


def pivot_data(request):
    dataset = Ingredients.objects.all()
    data = serializers.serialize('json', dataset)
    return JsonResponse(data, safe=False)


def index(request):
    recipe1 = Recipe.objects.all()[:6]
    recipe2 = Recipe.objects.order_by("-CreateDate")[:9]
    recipe3 = Recipe.objects.filter(rating__Rating="5")
    recipe4 = Rating.objects.all()
    recipe5 = Recipe.objects.all().count()
    recipe = {"recipe1": recipe1, "recipe2": recipe2, "recipe3": recipe3, "recipe4": recipe4, "recipe5": recipe5,
              "recipe": Recipe.objects.all()}
    return render(request, 'main/index.html', recipe)


def category(request):
    category = Category.objects.all()
    return render(request, 'main/category.html', {'category': category})


class categorycardDetailView(DetailView):
    model = Category
    context_object_name = 'category'
    template_name = 'main/categorycard.html'

    def get_context_data(self, **kwargs):
        context = super(categorycardDetailView, self).get_context_data(**kwargs)
        context['test'] = Recipe.objects.all()
        return context


class cardDetailView(DetailView):
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'main/card.html'

    def get_context_data(self, **kwargs):
        context = super(cardDetailView, self).get_context_data(**kwargs)
        context['test'] = Ingredients.objects.all()
        return context


def recom(request):
    recomendation = Recommendation.objects.all()
    return render(request, 'main/recomendation.html', {'recomendation': recomendation})


def dictionary(request):
    dictionary = Dictionary.objects.all()
    return render(request, 'main/dictionary.html', {'dictionary': dictionary})


def tablepr(request):
    tablepr1 = TypeIngredient.objects.all()
    tablepr2 = Ingredients.objects.all()
    tableproduct = {"tablepr1": tablepr1, "tablepr2": tablepr2}
    return render(request, 'main/tableproduct.html', tableproduct)


def createrecom(request):
    error = ''
    if request.method == 'POST':
        form = RecommendationForm(request.POST, request.FILES)
        if form.is_valid():
            thought = form.save(commit=False)
            thought.Userid = User.objects.get(pk=request.user.id)
            thought.save()
            redirect('recomendation/')
        else:
            error = 'Форма была неверной'

    form = RecommendationForm()
    createrecom = {
        'form': form,
        'error': error
    }
    return render(request, 'main/createrecom.html', createrecom)


def createrecipe(request):
    error = ''
    country1 = Country.objects.all()[:20]
    country2 = Country.objects.all()[20:40]
    country3 = Country.objects.all()[40:60]
    country4 = Country.objects.all()[60:80]
    if request.method == 'POST':
        form1 = RecipeForm(request.POST, request.FILES)
        if form1.is_valid():
            thought = form1.save(commit=False)
            thought.Userid = User.objects.get(pk=request.user.id)
            thought.save()
            redirect('createrecipe/')
        else:
            error = 'Форма была неверной'

    form1 = RecipeForm()
    createrecipe = {
        'form1': form1,
        'error': error,
        'country1': country1,
        'country2': country2,
        'country3': country3,
        'country4': country4
    }
    return render(request, 'main/createrecipe.html', createrecipe)


def equipmentTips(request):
    equipmentTips = EquipmentTips.objects.all()
    return render(request, 'main/equipmentTips.html', {'equipmentTips': equipmentTips})

course/main/templates/main/category.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Категории</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
      crossorigin="anonymous"
    />
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="{% static 'categorystyle/style.css' %}" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
  </head>
  <body>
    <header class="header-area">
      <div class="top-header-area">
        <div class="container h-100">
          <div class="row h-100 align-items-center justify-content-between">
            <div class="col-12 col-sm-6">
              <div class="breaking-news">
                <div id="breakingNewsTicker" class="ticker">
                  <ul>
                    {% if user.is_authenticated %}
                    <li><a href="#">Привет, {{ user.username }}!</a></li>
                    {% endif %}
                    <li>
                      <a href="#"
                        >Добро пожаловать на лучший сайт с рецептами!</a
                      >
                    </li>
                    <li><a href="#">Приятного аппетита!</a></li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-12 col-sm-6">
              <div class="top-social-info text-right">
                <a href="#"
                  ><i class="fa fa-pinterest" aria-hidden="true"></i
                ></a>
                <a href="#"
                  ><i class="fa fa-facebook" aria-hidden="true"></i
                ></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                <a href="#"
                  ><i class="fa fa-dribbble" aria-hidden="true"></i
                ></a>
                <a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a>
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}"
                  ><i aria-hidden="true">Log out</i></a
                >
                {% else %}
                <a href="{% url 'login' %}"><i aria-hidden="true">Log In</i></a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="delicious-main-menu">
        <div class="classy-nav-container breakpoint-off">
          <div class="container">
            <nav
              class="classy-navbar justify-content-between"
              id="deliciousNav"
            >
              <a class="nav-brand" href="../"
                ><img src="{% static 'img/core-img/logo.png' %}" alt=""
              /></a>
              <div class="classy-navbar-toggler">
                <span class="navbarToggler"
                  ><span></span><span></span><span></span
                ></span>
              </div>
              <div class="classy-menu">
                <div class="classycloseIcon">
                  <div class="cross-wrap">
                    <span class="top"></span><span class="bottom"></span>
                  </div>
                </div>
                <div class="classynav">
                  <ul>
                    <li><a href="../">Главная</a></li>
                    <li><a href="../equipmentTips/">Правила</a></li>
                    <li><a href="../dictionary/">Кулинарный словарь</a></li>
                    <li><a href="../recomendation/">Советы</a></li>
                    <li><a href="../tableproduct/">Таблица продуктов</a></li>
                    <li class="active"><a href="../category/">Категории</a></li>
                  </ul>
                </div>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </header>
    <div class="preloader d-flex align-items-center justify-content-center">
      <div class="preloader-content">
        <h3>Cooking in progress..</h3>
        <div id="cooking">
          <div class="bubble"></div>
          <div class="bubble"></div>
          <div class="bubble"></div>
          <div class="bubble"></div>
          <div class="bubble"></div>
          <div id="area">
            <div id="sides">
              <div id="pan"></div>
              <div id="handle"></div>
            </div>
            <div id="pancake">
              <div id="pastry"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="post-catagory section-padding-100">
      <div class="container">
        <div class="row">
          {% for el in category %}
          <div class="col-12 col-sm-6 col-lg-4">
            <div class="single-post-catagory mb-30">
              <img src="{{ el.Img.url }}" alt="" />
              <div class="catagory-content-bg">
                <div class="catagory-content">
                  <a href="{{ el.get_absolute_url }}" class="post-tag">Категория</a>
                  <a href="{{ el.get_absolute_url }}" class="post-title">{{ el.Name }}</a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <footer class="footer-area">
      <div class="container h-100">
        <div class="row h-100">
          <div
            class="
              col-12
              h-100
              d-flex
              flex-wrap
              align-items-center
              justify-content-between
            "
          >
            <div class="footer-social-info text-right">
              <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
              <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
              <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
              <a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a>
              <a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a>
              <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
            </div>
            <div class="footer-logo">
              <a href="../"
                ><img src="{% static 'img/core-img/logo.png' %}" alt=""
              /></a>
            </div>
            <p>
              <script>
                document.write(new Date().getFullYear());
              </script>
              Данный сайт выполнен в качестве курсового проекта студентами МПУ
              группы 191-361
            </p>
          </div>
        </div>
      </div>
    </footer>
    <script src="{% static 'categorystyle/js/jquery/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'categorystyle/js/active.js' %}"></script>
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/plugins/plugins.js' %}"></script>
    <script src="{% static 'js/active.js' %}"></script>
  </body>
</html>

course/main/templates/main/categorycard.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Категории</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
      crossorigin="anonymous"
    />
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="{% static 'categorystyle/style.css' %}" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
  </head>
  <body>
    <header class="header-area">
      <div class="top-header-area">
        <div class="container h-100">
          <div class="row h-100 align-items-center justify-content-between">
            <div class="col-12 col-sm-6">
              <div class="breaking-news">
                <div id="breakingNewsTicker" class="ticker">
                  <ul>
                    {% if user.is_authenticated %}
                    <li><a href="#">Привет, {{ user.username }}!</a></li>
                    {% endif %}
                    <li>
                      <a href="#"
                        >Добро пожаловать на лучший сайт с рецептами!</a
                      >
                    </li>
                    <li><a href="#">Приятного аппетита!</a></li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-12 col-sm-6">
              <div class="top-social-info text-right">
                <a href="#"
                  ><i class="fa fa-pinterest" aria-hidden="true"></i
                ></a>
                <a href="#"
                  ><i class="fa fa-facebook" aria-hidden="true"></i
                ></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                <a href="#"
                  ><i class="fa fa-dribbble" aria-hidden="true"></i
                ></a>
                <a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a>
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}"
                  ><i aria-hidden="true">Log out</i></a
                >
                {% else %}
                <a href="{% url 'login' %}"><i aria-hidden="true">Log In</i></a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="delicious-main-menu">
        <div class="classy-nav-container breakpoint-off">
          <div class="container">
            <nav
              class="classy-navbar justify-content-between"
              id="deliciousNav"
            >
              <a class="nav-brand" href="../../../"
                ><img src="{% static 'img/core-img/logo.png' %}" alt=""
              /></a>
              <div class="classy-navbar-toggler">
                <span class="navbarToggler"
                  ><span></span><span></span><span></span
                ></span>
              </div>
              <div class="classy-menu">
                <div class="classycloseIcon">
                  <div class="cross-wrap">
                    <span class="top"></span><span class="bottom"></span>
                  </div>
                </div>
                <div class="classynav">
                  <ul>
                    <li><a href="../../../">Главная</a></li>
                    <li><a href="../../../equipmentTips/">Правила</a></li>
                    <li><a href="../../../dictionary/">Кулинарный словарь</a></li>
                    <li><a href="../../../recomendation/">Советы</a></li>
                    <li><a href="../../../tableproduct/">Таблица продуктов</a></li>
                    <li><a href="../category/">Категории</a></li>
                  </ul>
                </div>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </header>
    <div class="preloader d-flex align-items-center justify-content-center">
      <div class="preloader-content">
        <h3>Cooking in progress..</h3>
        <div id="cooking">
          <div class="bubble"></div>
          <div class="bubble"></div>
          <div class="bubble"></div>
          <div class="bubble"></div>
          <div class="bubble"></div>
          <div id="area">
            <div id="sides">
              <div id="pan"></div>
              <div id="handle"></div>
            </div>
            <div id="pancake">
              <div id="pastry"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="post-catagory section-padding-100">
      <div class="container">
        <div class="row">
          {% for el in category.recipecategory_set.all %}
          <div class="col-12 col-sm-6 col-lg-6">
            <div class="single-post-catagory mb-30">
              {% for er in test %}
                {% if el.RecipeID_id == er.RecipeID %}
                  <img src="{{ er.Img.url }}" alt="" />
                    <div class="catagory-content-bg">
                      <div class="catagory-content">
                        <a href="{{ er.get_absolute_url }}" class="post-tag">Рецепт</a>
                        <a href="{{ er.get_absolute_url }}" class="post-title">{{ er.Name }}</a>
                      </div>
                    </div>
                {% endif %}
              {% endfor %}
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <footer class="footer-area">
      <div class="container h-100">
        <div class="row h-100">
          <div
            class="
              col-12
              h-100
              d-flex
              flex-wrap
              align-items-center
              justify-content-between
            "
          >
            <div class="footer-social-info text-right">
              <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
              <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
              <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
              <a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a>
              <a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a>
              <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
            </div>
            <div class="footer-logo">
              <a href="../../../"
                ><img src="{% static 'img/core-img/logo.png' %}" alt=""
              /></a>
            </div>
            <p>
              <script>
                document.write(new Date().getFullYear());
              </script>
              Данный сайт выполнен в качестве курсового проекта студентами МПУ
              группы 191-361
            </p>
          </div>
        </div>
      </div>
    </footer>
    <script src="{% static 'categorystyle/js/jquery/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'categorystyle/js/active.js' %}"></script>
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/plugins/plugins.js' %}"></script>
    <script src="{% static 'js/active.js' %}"></script>
  </body>
</html>

course/main/templates/main/dashboard_with_pivot.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Dashboard with Flexmonster</title>
  <script src="https://cdn.flexmonster.com/flexmonster.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <link rel="stylesheet" href="https://cdn.flexmonster.com/demo.css">
</head>
<body>
<div id="pivot-table-container" data-url="{% url 'pivot_data' %}"></div>
<div id="pivot-chart-container"></div>
<script>
function processData(dataset) {
    var result = []
    dataset = JSON.parse(dataset);
    dataset.forEach(item => result.push(item.fields));
    return result;
}
$.ajax({
    url: $("#pivot-table-container").attr("data-url"),
    dataType: 'json',
    success: function(data) {
        new Flexmonster({
            container: "#pivot-table-container",
            componentFolder: "https://cdn.flexmonster.com/",
            width: "100%",
            height: 430,
            toolbar: true,
            report: {
                dataSource: {
                    type: "json",
                    data: processData(data)
                },
                slice: {}
            }
        });
        new Flexmonster({
            container: "#pivot-chart-container",
            componentFolder: "https://cdn.flexmonster.com/",
            width: "100%",
            height: 430,
            //toolbar: true,
            report: {
                dataSource: {
                    type: "json",
                    data: processData(data)
                },
                slice: {},
                "options": {
                    "viewType": "charts",
                    "chart": {
                        "type": "pie"
                    }
                }
            }
        });
    }
});
</script>
</body>
</html>